[package]
name = "rusthacking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7.4", features = ["http2"] }
axum-prometheus = "0.6.1"
deadpool-diesel = { version = "0.5.0", features = ["tracing", "sqlite"] }
diesel = { version = "2.1.4", features = ["sqlite"] }
metrics-process = "1.2.0"
serde = { version = "1.0.196", features = ["derive"] }
tokio = { version = "1.35.1", features = ["full", "tracing"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["json", "env-filter"] }
